# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DebtSnowBallGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 400, 631, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 440, 621, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 360, 621, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.extraCash = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.extraCash.setFont(font)
        self.extraCash.setObjectName("extraCash")
        self.horizontalLayout_2.addWidget(self.extraCash)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(50, 10, 621, 334))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget1.setFont(font)
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 10, 1)
        self.p1 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p1.setFont(font)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 1, 1, 1, 1)
        self.i1 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i1.setFont(font)
        self.i1.setObjectName("i1")
        self.gridLayout.addWidget(self.i1, 1, 2, 1, 1)
        self.m1 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m1.setFont(font)
        self.m1.setObjectName("m1")
        self.gridLayout.addWidget(self.m1, 1, 3, 1, 1)
        self.p2 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p2.setFont(font)
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 2, 1, 1, 1)
        self.i2 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2.setFont(font)
        self.i2.setObjectName("i2")
        self.gridLayout.addWidget(self.i2, 2, 2, 1, 1)
        self.m2 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m2.setFont(font)
        self.m2.setObjectName("m2")
        self.gridLayout.addWidget(self.m2, 2, 3, 1, 1)
        self.p3 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p3.setFont(font)
        self.p3.setObjectName("p3")
        self.gridLayout.addWidget(self.p3, 3, 1, 1, 1)
        self.i3 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i3.setFont(font)
        self.i3.setObjectName("i3")
        self.gridLayout.addWidget(self.i3, 3, 2, 1, 1)
        self.m3 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m3.setFont(font)
        self.m3.setObjectName("m3")
        self.gridLayout.addWidget(self.m3, 3, 3, 1, 1)
        self.p4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p4.setFont(font)
        self.p4.setObjectName("p4")
        self.gridLayout.addWidget(self.p4, 4, 1, 1, 1)
        self.i4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i4.setFont(font)
        self.i4.setObjectName("i4")
        self.gridLayout.addWidget(self.i4, 4, 2, 1, 1)
        self.m4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m4.setFont(font)
        self.m4.setObjectName("m4")
        self.gridLayout.addWidget(self.m4, 4, 3, 1, 1)
        self.p5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p5.setFont(font)
        self.p5.setObjectName("p5")
        self.gridLayout.addWidget(self.p5, 5, 1, 1, 1)
        self.i5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i5.setFont(font)
        self.i5.setObjectName("i5")
        self.gridLayout.addWidget(self.i5, 5, 2, 1, 1)
        self.m5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m5.setFont(font)
        self.m5.setObjectName("m5")
        self.gridLayout.addWidget(self.m5, 5, 3, 1, 1)
        self.p6 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p6.setFont(font)
        self.p6.setObjectName("p6")
        self.gridLayout.addWidget(self.p6, 6, 1, 1, 1)
        self.i6 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i6.setFont(font)
        self.i6.setObjectName("i6")
        self.gridLayout.addWidget(self.i6, 6, 2, 1, 1)
        self.m6 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m6.setFont(font)
        self.m6.setObjectName("m6")
        self.gridLayout.addWidget(self.m6, 6, 3, 1, 1)
        self.p7 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p7.setFont(font)
        self.p7.setObjectName("p7")
        self.gridLayout.addWidget(self.p7, 7, 1, 1, 1)
        self.i7 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i7.setFont(font)
        self.i7.setObjectName("i7")
        self.gridLayout.addWidget(self.i7, 7, 2, 1, 1)
        self.m7 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m7.setFont(font)
        self.m7.setObjectName("m7")
        self.gridLayout.addWidget(self.m7, 7, 3, 1, 1)
        self.p8 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p8.setFont(font)
        self.p8.setObjectName("p8")
        self.gridLayout.addWidget(self.p8, 8, 1, 1, 1)
        self.i8 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i8.setFont(font)
        self.i8.setObjectName("i8")
        self.gridLayout.addWidget(self.i8, 8, 2, 1, 1)
        self.m8 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m8.setFont(font)
        self.m8.setObjectName("m8")
        self.gridLayout.addWidget(self.m8, 8, 3, 1, 1)
        self.p9 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p9.setFont(font)
        self.p9.setObjectName("p9")
        self.gridLayout.addWidget(self.p9, 9, 1, 1, 1)
        self.i9 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i9.setFont(font)
        self.i9.setObjectName("i9")
        self.gridLayout.addWidget(self.i9, 9, 2, 1, 1)
        self.m9 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m9.setFont(font)
        self.m9.setObjectName("m9")
        self.gridLayout.addWidget(self.m9, 9, 3, 1, 1)
        self.p10 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p10.setFont(font)
        self.p10.setObjectName("p10")
        self.gridLayout.addWidget(self.p10, 10, 1, 1, 1)
        self.i10 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i10.setFont(font)
        self.i10.setObjectName("i10")
        self.gridLayout.addWidget(self.i10, 10, 2, 1, 1)
        self.m10 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.m10.setFont(font)
        self.m10.setObjectName("m10")
        self.gridLayout.addWidget(self.m10, 10, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Debt Snowballin\'"))
        self.pushButton.setText(_translate("MainWindow", "Calculate Time to Paid off and Interest Saved"))
        self.label_14.setText(_translate("MainWindow", "Amount Extra To Pay Each Year"))
        self.label.setText(_translate("MainWindow", "Principle"))
        self.label_2.setText(_translate("MainWindow", "Interest"))
        self.label_3.setText(_translate("MainWindow", "Min Payment per Month"))
        self.label_4.setText(_translate("MainWindow", "Debt 1"))
        self.label_5.setText(_translate("MainWindow", "Debt  2"))
        self.label_6.setText(_translate("MainWindow", "Debt  3"))
        self.label_7.setText(_translate("MainWindow", "Debt  4"))
        self.label_8.setText(_translate("MainWindow", "Debt  5"))
        self.label_9.setText(_translate("MainWindow", "Debt  6"))
        self.label_10.setText(_translate("MainWindow", "Debt  7"))
        self.label_11.setText(_translate("MainWindow", "Debt  8"))
        self.label_12.setText(_translate("MainWindow", "Debt  9"))
        self.label_13.setText(_translate("MainWindow", "Debt  10"))

